sudo: required

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - sleep 5
  - npm run build &
  - npm run server &
  - sleep 3
  - firefox http://localhost:5777/utest/ &
  - sleep 7
 
script:
  - "npm test"
  
language: node_js

node_js:
  - "10.1.0"
